### ISSUE TITLE
why it's report an error 'Error, unexpected file format' when rebuild

### ISSUE THREAD

**Issue by alphayan** [recoilme/sniper#10]
I use sniper `sniper.Open(sniper.Dir("server_sniper"))` ,it's run well,I use windows coding and  run  it in linux.

when I build the code for a new version and run  it in the same directory,it run bad,I don't know why it's report an error `Error, unexpected file format`

I must remove the directory `server_sniper` then it run well

**Comment by recoilme** [comment]
Sorry for longtime response

Do you have this error when upgrade sniper library?

**Comment by alphayan** [comment]
> Sorry for longtime response
> 
> Do you have this error when upgrade sniper library or when move database created on windows to linux?
Thanks for reply,I just build my program  cross-compile on win10 x64 for linux x64,I don't move database on windows to linux,the program use the old database on linux which the old program version created.

**Comment by alphayan** [comment]
> Sorry for longtime response
> 
> Do you have this error when upgrade sniper library or when move database created on windows to linux?

Thanks for reply,I just build my program cross-compile on win10 x64 for linux x64,I don't move database on windows to linux,the program use the old database on linux which the old program version created.

**Comment by recoilme** [comment]
ErrFormat now wrapped with detailed information about low level error (master branch): [https://github.com/recoilme/sniper/pull/11](https://github.com/recoilme/sniper/pull/11) 
Looks like something went wrong during database closing(

**Comment by alphayan** [comment]
> ErrFormat now wrapped with detailed information about low level error (master branch): #11
> Looks like something went wrong during database closing(

Oh this panic with `panic: len(key) == 0: Error, unexpected file format`
It seems like  I set an  empty key then sniper return this error

**Comment by recoilme** [comment]
Please check with latest master - https://github.com/recoilme/sniper/pull/12

**Comment by alphayan** [comment]
> Please check with latest master - #12

OK I'll try it,thanks for reply
