### ISSUE TITLE
Very fast kv storage!

### ISSUE THREAD

**Issue by tbocek** [recoilme/sniper#15]
Hi,

I just tested your library and its incredible fast. I started with badger, which I could not use as I would run out of disk space (I only have 1 TB). Then I tried pogreb, which was too slow during inserts, but it was efficient with disk space, it used ~20G. Now I'm trying sniper and its fast and disk space efficient (also ~20G)!

I wonder why is there no store.Key() that iterates over all keys. There is one for if a bucket is provided. Also why did you chose to have Put with and without a bucket? 

You also mentioned: 512 Kb - maximum entry size len(key) + len(value). What is the limiting factor?

In the examples you set: sniper.Open(sniper.Dir("1"), sniper.ChunksCollision(2), sniper.ChunksTotal(10)). What effects do these parameters have?

**Comment by recoilme** [comment]
Hi,

 - I wonder why is there no store.Key() that iterates over all keys
It may be implemented but it will use fullscan -  its slow and usually very expensive (if you store billions of keys)

 -  There is one for if a bucket is provided
Set don't store keys in memory (only hash), but put - store all key. Put/Bucket give ability to iterate over keys, but with memory cost. Put & bucket use https://github.com/recoilme/sortedset internally

 - 512 Kb - maximum entry size
4 byte for storing chunk size (for minimizing memory usage)

 - sniper.Dir("1"), sniper.ChunksCollision(2), sniper.ChunksTotal(10)
Dir - directory
ChunksCollision - chunks for collisions, default 4 (billions of keys without collisions)
ChunksTotal - chunks for data, default 256 (maximum Tb)

256 chunks ~ 1Tb max db size
1024 chunks ~ 4Tb max db size (more chunks - more space for data)

P.S.: use versioned api pls, we may change api in future

**Comment by recoilme** [comment]
- 512 Kb - maximum entry size
 
 Oops, it's looks outdated readme, i will check, current limits:
 - keylen uint16
 - vallen uint32
 
https://github.com/recoilme/sniper/blob/master/chunk.go#L38

**Comment by tbocek** [comment]
>>I wonder why is there no store.Key() that iterates over all keys

>It may be implemented but it will use fullscan - its slow and usually very expensive (if you store billions of keys)

I see, just wondering. My use case for iterating over keys is for my testcases and for debugging. I store/remove/update data and check if everything is there.
