### ISSUE TITLE
Clarification request - this is a single system KV store, not a distributed KV store, right ?

### ISSUE THREAD

**Issue by bdutta** [recoilme/sniper#16]
Based on a quick look around, I get the impression that `sniper` is a local KV store and not a distributed, network accessible KV store (like Redis, CouchDB, MongoDB etc.), i.e. more like `sqlite` (in the RDBMS world). Is this correct ? Of course, one could wrap `sniper` with a REST API to turn it into a service, but then it'd be a single-point-of-failure i.e. no high-availability.

**Comment by recoilme** [comment]
Yes, you right, sniper is low level engine
For server you may try something like this https://github.com/recoilme/b52
